language: csharp
solution: solution-name.sln
install:
  - nuget restore NorthWind.Web.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release NorthWind.Web.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Northwind.Service.Test/bin/Release/Northwind.Service.Test.dll